# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Boilerplate
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  target 'BoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

