# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'client_dealme_today' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for client_dealme_today
   pod 'GoogleSignIn', '~> 4.4.0'
   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'client_dealme_todayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
